### ISSUE TITLE
How to you actually use this package

### ISSUE THREAD

**Issue by balajirama** [lucastheisen/pod-confluence#2]
Hi Lucas,

I am trying to see if it is possible to use your package to generate Confluence pages from POD and serve the pages on my company's confluence server. Could you help in this? I am trying to find out what all your code really does. The Synopsis is not very clear. I understand the space key part, but what is the structure storage markdown scalar variable meant for? Will you generate a markdown string? Would I then need to write this to a file? Should this be done for each Perl module that will be in this space?

Thanks,
Balaji

**Comment by lucastheisen** [comment]
This project is basically stale in that i haven't updated it in 4 years (nor used it in 3).  That said, i did use it for a couple of years to regenerate a Confluence site based upon my pod documentation in my projects.  I can say it does not generate markdown.  It generates the _source xml_ that you see if you open a confluence page in source mode.  Feel free to use the code as you see fit, but i have no intention of updating this project moving forward.
